services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poll_user -d poll_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: affordmed_backend
    environment:
      DATABASE_URL: postgresql://poll_user:poll_password@postgres:5432/poll_db?schema=public
      FRONTEND_ORIGIN: http://localhost:5173
      PORT: '3000'
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
